spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adminsystem?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: com.thtf.conf.MySQL5DialectUTF8
server:
  port: 8095
image:
  path: D:\\Development\\apache-tomcat-7.0.81-windows-x64\\apache-tomcat-7.0.81\\webapps\\adminsystem\\easyui_demo\\easyuidemo\\image\\
  serverpath: http://localhost:8080/adminsystem/easyui_demo/easyuidemo/image/
  zhongzhuanhtml: http://localhost:8080/adminsystem/easyui_demo/easyuidemo/temp/getimage.html